release: yes "yes" | python manage.py migrate
web: uwsgi --http-socket=:$PORT --master --workers=2 --threads=8 --die-on-term --wsgi-file=webaup/wsgi.py  --static-map /media/=/app/webaup/media/ --offload-threads 1
