# Generated by Django 4.1.5 on 2023-01-03 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("blog", "0006_rename_blogpeoplerelationship_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogindexpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Somente modo paisagem; largura horizontal entre 1000px e 3000px.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="introduction",
            field=models.TextField(
                blank=True, help_text="Texto para descrever a página"
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="date_published",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de publicação do artigo"
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Somente modo paisagem; largura horizontal entre 1000px e 3000px.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="introduction",
            field=models.TextField(
                blank=True, help_text="Texto para descrever a página"
            ),
        ),
    ]
