# Generated by Django 4.1.6 on 2023-02-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_blogindexpage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="last_modified",
            field=models.DateField(
                auto_now=True, verbose_name="Data de atualização do artigo"
            ),
        ),
    ]
