# Generated by Django 4.1.5 on 2023-01-03 20:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("locations", "0005_use_json_field_for_body_streamfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationoperatinghours",
            name="closed",
            field=models.BooleanField(
                blank=True,
                help_text="Marque se o local estiver fechado neste dia",
                verbose_name="Closed?",
            ),
        ),
        migrations.AlterField(
            model_name="locationpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Somente modo paisagem; largura horizontal entre 1000px and 3000px.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="locationpage",
            name="introduction",
            field=models.TextField(
                blank=True, help_text="Texto para descrever a página"
            ),
        ),
        migrations.AlterField(
            model_name="locationpage",
            name="lat_long",
            field=models.CharField(
                help_text="Separados por vírgula lat/long. (Ex. 64.144367, -21.939182)                    Clique com o botão direito do mouse em Google Maps e selecione 'O que é aqui'",
                max_length=36,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_lat_long",
                        message="Latitude e Longetitude deve ser um numérico separado por vírgula",
                        regex="^(\\-?\\d+(\\.\\d+)?),\\s*(\\-?\\d+(\\.\\d+)?)$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="locationsindexpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Somente modo paisagem; largura horizontal entre 1000px and 3000px.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="locationsindexpage",
            name="introduction",
            field=models.TextField(
                blank=True, help_text="Texto para descrever a página"
            ),
        ),
    ]
