# Generated by Django 4.1.6 on 2023-03-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_alter_locationoperatinghours_closed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationoperatinghours",
            name="day",
            field=models.CharField(
                choices=[
                    ("SEG", "Segunda-Feira"),
                    ("TER", "Terça-Feira"),
                    ("QUA", "Quarta-Feira"),
                    ("QUI", "Quinta-Feira"),
                    ("SEX", "Sexta-Feira"),
                    ("SAB", "Sábado"),
                    ("DOM", "Domingo"),
                ],
                default="SEG",
                max_length=4,
            ),
        ),
    ]
