# Generated by Django 4.1.6 on 2023-03-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0008_locationpage_email_locationpage_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationpage",
            name="titulo",
            field=models.TextField(help_text="nome do local", null="True"),
            preserve_default="True",
        ),
    ]
