# Generated by Django 4.1.6 on 2023-03-23 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0009_locationpage_titulo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locationpage",
            name="titulo",
        ),
    ]
