# Generated by Django 4.1.6 on 2023-03-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("breads", "0006_breadingredient_expire_at_breadingredient_expired_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Locais de Origem"},
        ),
    ]
