# Generated by Django 4.1.6 on 2023-03-22 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0008_locationpage_email_locationpage_phone"),
        ("breads", "0008_remove_breadpage_origin_breadpage_origin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={},
        ),
        migrations.AddField(
            model_name="country",
            name="locais",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.locationpage",
            ),
        ),
    ]
