# Generated by Django 4.1.6 on 2023-03-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("breads", "0009_alter_country_options_country_locais"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="locais",
            new_name="countries",
        ),
        migrations.RemoveField(
            model_name="country",
            name="title",
        ),
    ]
