# Generated by Django 4.1.6 on 2023-03-23 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0008_locationpage_email_locationpage_phone"),
        ("breads", "0011_alter_country_countries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="countries",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "class": "LocationPage",
                    "content_type__app_label": "locations",
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.locationpage",
            ),
        ),
    ]
