# Generated by Django 4.1.6 on 2023-03-23 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("breads", "0014_alter_country_options_country_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="countries",
        ),
    ]
