# Generated by Django 4.1.6 on 2023-03-23 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0010_remove_locationpage_titulo"),
        ("breads", "0015_remove_country_countries"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="countries",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.locationpage",
            ),
        ),
    ]
